### ISSUE TITLE
Email and image fields

### ISSUE THREAD

**Issue by Olsz4k** [RostiMelk/ACF-Tools#2]
First - very good and usefull extension :)

I found two 'bugs' when using.

1. E-mail field:
I got field with name 'email_adress'. When i copy code, i'm getting this:

`the_field('email_adress'); `

should't i get it like this?

` if ( $email_adress= get_field('email_adress') ): 
	 echo $email_adress; 
endif; `

2. Image field:
Every time our variable name for image is "$image". Shouldn't it be taken from field name? For example when i have field called 'icon' it should be:

`
$icon= get_sub_field('icon');
if( !empty( $icon) ): 
	<img src="echo esc_url($icon['url']); " alt="echo esc_attr($icon['alt']); " />
 endif;`

instead of

`
$image = get_sub_field('icon');
if( !empty( $image ) ): 
	<img src="echo esc_url($image['url']); " alt="echo esc_attr($image['alt']); " />
endif; `

**Comment by RostiMelk** [comment]
Thank you for your feedback!

I just pushed a new version.

**Email field will now include HTML and a conditional statement.**
Example:
```
<?php if ( $contact = get_field('contact') ): ?>
	<a href="mailto:<?php echo $contact; ?>"><?php echo $contact; ?></a>
<?php endif; ?>
```

**Image field will now use field name as a variable instead of a fixed $image variable.**
Example:
```
<?php
$article_image = get_field('article_image');
$size = 'full';
if( $article_image ) {
	$url = wp_get_attachment_url( $article_image );
	echo wp_get_attachment_image( $article_image, $size );
}; ?>
```

I also just submitted the new version to the Google Web Store, but it will take a couple of days for them to approve it.
