### ISSUE TITLE
"=" forgotten ?

### ISSUE THREAD

**Issue by nicleg** [RostiMelk/ACF-Tools#35]
Hi,
 and thank you for the acf firefox extension.

I'm perhaps not that much developper as you, but I notice perhaps an error.

In the ACF plugin page, in a group of field, with a field with a repeater (3 fields inside : text, content editor, text).
So the "Copy code with sub fields" button appears on hover of the line.
When you click on it, the copied text looks like that : 

`<?php if ( have_rows( 'sections_textes' ) ) : ?>
	<?php while ( have_rows( 'sections_textes' ) ) :
		the_row(); ?>
		
		<?php if ( $home-section-title = get_sub_field( 'home-section-title' ) ) : ?>
			<?php echo esc_html( $home-section-title ); ?>
		<?php endif; ?>

		<?php if ( $home-section-text = get_sub_field( 'home-section-text' ) ) : ?>
			<?php echo $home-section-text; ?>
		<?php endif; ?>

		<?php if ( $home-section-button = get_sub_field( 'home-section-button' ) ) : ?>
			<?php echo esc_html( $home-section-button ); ?>
		<?php endif; ?>

	<?php endwhile; ?>
<?php endif; ?>`

Shouldn't the "=" be "==" ?

I hope it's helps, either I wrotte all of this for nothing !
Nicolas.

**Comment by RostiMelk** [comment]
Hi!

If you are reffering to the variables that are set to the acf fields functions if the if statements, then no. 
They should be `=` and not `==` as I am setting a new variable and not comparing data.

Edit:
One more thing.
You cannot use hyphens(dashes) in php variables. I also recommend setting field names with underscores instead of hyphens, as ACF tools doesn't take hyphens into account when creating php variables (yet).

**Comment by nicleg** [comment]
Sorry, I had an error an I thoughth it came from here but I now completly understood.
Thank's !
